"use client";
import { useMemo, useState } from "react";
import { SiteLayout } from "@/components/layout";
import { SectionTitle } from "@/components/section-title";
import { allTeams } from "@/lib/data";
import { getBestXI } from "@/lib/fantasy";
import type { Formation } from "@/types";
const formations: Formation[] = ["4-3-3", "4-4-2", "3-5-2", "4-2-3-1", "3-4-3"];
export default function MejorXIPage() { const [formation, setFormation] = useState<Formation>("4-3-3"); const best = useMemo(() => getBestXI(formation), [formation]); const total = best.reduce((sum, player) => sum + player.fantasyScore, 0).toFixed(1); return <SiteLayout><section className="container-shell py-12"><SectionTitle eyebrow="Mejor XI" title="Generador automático del mejor once" description="Selecciona una formación y el algoritmo compone el once con mayor puntuación fantasy estimada." /><div className="card mb-6 flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-sm text-muted">Formación activa</p><div className="mt-2 flex flex-wrap gap-2">{formations.map((item) => <button key={item} onClick={() => setFormation(item)} className={`rounded-full px-4 py-2 text-sm font-semibold transition ${formation === item ? 'bg-primary text-white' : 'border border-border hover:border-primary hover:text-primary'}`}>{item}</button>)}</div></div><div className="text-right"><p className="text-sm text-muted">Score total estimado</p><p className="text-3xl font-bold">{total}</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{best.map((player) => { const team = allTeams.find((item) => item.id === player.teamId); return <article key={player.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-muted">{player.position}</p><h3 className="text-xl font-bold">{player.name}</h3><p className="mt-1 text-sm text-muted">{team?.flag} {team?.name} · {player.club}</p></div><span className="badge-soft">{player.fantasyScore}</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm text-muted"><div className="rounded-xl bg-panel p-3">Gol: {player.goalProbability}%</div><div className="rounded-xl bg-panel p-3">Asistencia: {player.assistProbability}%</div><div className="rounded-xl bg-panel p-3">Titularidad: {player.starterProbability}%</div><div className="rounded-xl bg-panel p-3">Valor: {player.fantasyValue.toFixed(1)}M</div></div></article>; })}</div></section></SiteLayout>; }
