"use client";
import { useMemo, useState } from "react";
import { SiteLayout } from "@/components/layout";
import { SectionTitle } from "@/components/section-title";
import { allTeams } from "@/lib/data";
import { getRecommendedSquad } from "@/lib/fantasy";
import type { Formation } from "@/types";
const formations: Formation[] = ["4-3-3", "4-4-2", "3-5-2", "4-2-3-1", "3-4-3"];
export default function ConstructorPage() { const [formation, setFormation] = useState<Formation>("4-3-3"); const [budget, setBudget] = useState(95); const squad = useMemo(() => getRecommendedSquad(formation, budget), [formation, budget]); return <SiteLayout><section className="container-shell py-12"><SectionTitle eyebrow="Constructor" title="Constructor automático de equipo" description="Elige formación y presupuesto para recibir una recomendación optimizada por valor fantasy estimado." /><div className="card mb-6 grid gap-4 p-5 lg:grid-cols-[1fr_1fr_0.6fr]"><div><label className="mb-2 block text-sm font-semibold">Formación</label><select value={formation} onChange={(event) => setFormation(event.target.value as Formation)} className="w-full rounded-xl border border-border bg-white px-4 py-3 outline-none focus:border-primary">{formations.map((item) => <option key={item} value={item}>{item}</option>)}</select></div><div><label className="mb-2 block text-sm font-semibold">Presupuesto: {budget.toFixed(1)}M</label><input type="range" min="70" max="120" step="0.5" value={budget} onChange={(event) => setBudget(Number(event.target.value))} className="w-full accent-primary" /></div><div className="rounded-2xl bg-panel p-4"><p className="text-sm text-muted">Resumen</p><p className="mt-2 text-xl font-bold">{squad.totalCost.toFixed(1)}M</p><p className="text-sm text-muted">Score total {squad.totalScore}</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{squad.players.map((player) => { const team = allTeams.find((item) => item.id === player.teamId); return <article key={player.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-muted">{player.position}</p><h3 className="text-xl font-bold">{player.name}</h3><p className="mt-1 text-sm text-muted">{team?.flag} {team?.shortName} · {player.club}</p></div><span className="badge-soft">{player.fantasyScore}</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm text-muted"><div className="rounded-xl bg-panel p-3">Valor: {player.fantasyValue.toFixed(1)}M</div><div className="rounded-xl bg-panel p-3">Gol: {player.goalProbability}%</div><div className="rounded-xl bg-panel p-3">Asistencia: {player.assistProbability}%</div><div className="rounded-xl bg-panel p-3">Avance: {player.advanceProbability}%</div></div></article>; })}</div></section></SiteLayout>; }
